Repository grafana/beyla, pull requests merged in 2023-09, with the labels that each got.

#256 Fix Beyla CTRL+C shutdown. Also simplify pipeline
  pkg/beyla/beyla.go
  pkg/internal/ebpf/common/common.go
  pkg/internal/ebpf/common/ringbuf.go
  pkg/internal/ebpf/common/ringbuf_test.go
  pkg/internal/ebpf/common/spanner.go
  pkg/internal/ebpf/common/spanner_test.go
  pkg/internal/ebpf/goruntime/goruntime.go
  pkg/internal/ebpf/grpc/grpc.go
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/httpfltr/httpfltr_test.go
  pkg/internal/ebpf/httpfltr/httpfltr_transform.go
  pkg/internal/ebpf/httpfltr/httpfltr_transform_test.go
  pkg/internal/ebpf/nethttp/nethttp.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/ebpf/tracer_darwin.go
  pkg/internal/export/debug/debug.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/export/prom/prom.go
  pkg/internal/pipe/instrumenter.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/request/span.go
  pkg/internal/traces/reader.go
  pkg/internal/transform/k8s.go
  pkg/internal/transform/routes.go
  pkg/internal/transform/routes_test.go
  pkg/internal/transform/spanner.go
Labels: bug

#269 Add more introductory content for the main docs page
  docs/sources/_index.md
  docs/sources/requesttime.md
Labels: documentation

#271 Dynamically generate OTEL exporters for each traced service
  docs/sources/configure/options.md
  go.mod
  go.sum
  pkg/internal/ebpf/common/ringbuf.go
  pkg/internal/ebpf/common/ringbuf_test.go
  pkg/internal/ebpf/finder.go
  pkg/internal/ebpf/goruntime/goruntime.go
  pkg/internal/ebpf/grpc/grpc.go
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/nethttp/nethttp.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/export/prom/prom.go
  pkg/internal/pipe/config.go
  pkg/internal/pipe/config_test.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/traces/reader.go
  test/integration/components/testserver/testserver.go
  test/integration/configs/instrumenter-config-override-svcname.yml
  test/integration/red_test.go
  test/integration/red_test_java.go
  test/integration/suites_test.go
  test/integration/traces_test.go
  vendor/github.com/caarlos0/env/v9/.gitignore
  vendor/github.com/caarlos0/env/v9/.golangci.yml
  vendor/github.com/caarlos0/env/v9/.goreleaser.yml
  vendor/github.com/caarlos0/env/v9/.mailmap
  vendor/github.com/caarlos0/env/v9/LICENSE.md
  vendor/github.com/caarlos0/env/v9/Makefile
  vendor/github.com/caarlos0/env/v9/README.md
  vendor/github.com/caarlos0/env/v9/env.go
  vendor/github.com/caarlos0/env/v9/env_tomap.go
  vendor/github.com/caarlos0/env/v9/env_tomap_windows.go
  vendor/github.com/caarlos0/env/v9/error.go
  vendor/modules.txt
Labels: breaking-change

#300 Modifying how we handle OTEL traces/metrics endpoints
  docs/sources/configure/options.md
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/common_test.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/pipe/config_test.go
Labels: breaking-change

#305 Add more logos to the docs page
  docs/sources/_index.md
  docs/sources/configure/_index.md
  docs/sources/setup/_index.md
  docs/sources/tutorial/index.md
Labels: documentation

#312 move YAML open_port, executable_name and system_wide options to top level
  docs/sources/configure/export-modes.md
  docs/sources/configure/options.md
  docs/sources/configure/resources/instrumenter-config.yml
  docs/sources/setup/standalone.md
  pkg/beyla/beyla.go
  pkg/internal/ebpf/common/common.go
  pkg/internal/ebpf/finder.go
  pkg/internal/ebpf/finder_darwin.go
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/httpfltr/httpfltr_test.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/pipe/config.go
  pkg/internal/pipe/config_test.go
Labels: breaking-change

#309 Make beyla work with statically, externally-linked executables and CGO
  pkg/internal/ebpf/instrumenter.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/goexec/instructions.go
  pkg/internal/goexec/structmembers.go
  test/integration/components/testserver/Dockerfile_static
  test/integration/suites_test.go
Labels: bug

#321 Trace span status
  docs/sources/configure/options.md
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/pipe/config.go
  pkg/internal/pipe/config_test.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/transform/routes.go
  pkg/internal/transform/routes_test.go
  test/integration/traces_test.go
Labels: breaking-change
