Repository grafana/beyla, pull requests merged in 2023-10, with the labels that each got.

#324 Integrate multi-service selector
  Makefile
  docs/sources/configure/options.md
  pkg/beyla/beyla.go
  pkg/internal/ebpf/common/ringbuf.go
  pkg/internal/ebpf/common/ringbuf_test.go
  pkg/internal/ebpf/finder.go
  pkg/internal/ebpf/goruntime/goruntime.go
  pkg/internal/ebpf/grpc/grpc.go
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/httpfltr/httpfltr_transform.go
  pkg/internal/ebpf/httpfltr/httpfltr_transform_test.go
  pkg/internal/ebpf/nethttp/nethttp.go
  pkg/internal/ebpf/services/criteria.go
  pkg/internal/ebpf/services/criteria_test.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/exec/file.go
  pkg/internal/export/debug/debug.go
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/export/prom/prom.go
  pkg/internal/pipe/config.go
  pkg/internal/pipe/config_test.go
  pkg/internal/pipe/global/context.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/request/span.go
  pkg/internal/svc/svc.go
  test/integration/components/nodejsserver/app.js
  test/integration/configs/instrumenter-config-node.yml
  test/integration/docker-compose-nodejs.yml
  test/integration/docker-compose.yml
  test/integration/suites_test.go
  test/integration/traces_test.go
Labels: breaking-change

#348 Add more branding to docs
  docs/sources/setup/standalone.md
Labels: documentation

#371 Avoid duplication/triplication/n-plication of traces for the same process
  pkg/internal/discover/attacher.go
  pkg/internal/discover/typer.go
  test/integration/components/testserver/Dockerfile_duplicate
  test/integration/components/testserver/duplicate_testserver.sh
  test/integration/docker-compose-multiexec.yml
  test/integration/multiprocess_test.go
  test/integration/suites_test.go
Labels: bug

#372 Add feature which allows paths to be ignored
  docs/sources/configure/options.md
  examples/greeting-apps/configs/beyla-config.yml
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/traces.go
  pkg/internal/request/span.go
  pkg/internal/transform/route/matcher.go
  pkg/internal/transform/route/matcher_test.go
  pkg/internal/transform/routes.go
  pkg/internal/transform/routes_test.go
  test/integration/configs/instrumenter-config-grpc-export.yml
  test/integration/configs/instrumenter-config-java-host.yml
  test/integration/configs/instrumenter-config-java.yml
  test/integration/configs/instrumenter-config-multiexec.yml
  test/integration/configs/instrumenter-config-no-route.yml
  test/integration/configs/instrumenter-config-node.yml
  test/integration/configs/instrumenter-config-override-svcname.yml
  test/integration/configs/instrumenter-config-promscrape.yml
  test/integration/configs/instrumenter-config-ruby.yml
  test/integration/configs/instrumenter-config.yml
  test/integration/red_test.go
  test/integration/traces_test.go
  test/oats/configs/instrumenter-config-traces.yml
Labels: enhancement, breaking-change

#393 Avoid instrumenting service managers
  pkg/internal/discover/attacher.go
  pkg/internal/discover/typer.go
Labels: bug

#398 Fix nil-pointer panics on missing executable sections
  pkg/internal/discover/attacher.go
  pkg/internal/goexec/instructions.go
Labels: bug
