Repository grafana/beyla, pull requests merged in 2023-04, with the labels that each got.

#47 Update license to APLv2
  LICENSE
  bpf/go_nethttp.c
Labels: bug, documentation

#48 Revert back license for bpf so it can load
  bpf/go_nethttp.c
Labels: bug, documentation

#46 Add Go gGPC probes for metrics and traces
  .gitignore
  Makefile
  bpf/go_byte_arr.h
  bpf/go_nethttp.c
  configs/offsets/tracker_input.json
  pkg/ebpf/nethttp/bpf_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/ebpf/nethttp/nethttp.go
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/goexec/offsets.go
  pkg/goexec/offsets.json
  pkg/goexec/structmembers.go
  pkg/goexec/structmembers_test.go
  pkg/pipe/config.go
  pkg/pipe/config_test.go
  pkg/pipe/instrumenter.go
  pkg/pipe/instrumenter_test.go
  pkg/transform/spanner.go
  pkg/transform/spanner_test.go
  test/integration/components/testserver/grpc/client/client.go
  test/integration/components/testserver/grpc/routeguide/route_guide.pb.go
  test/integration/components/testserver/grpc/routeguide/route_guide.proto
  test/integration/components/testserver/grpc/routeguide/route_guide_grpc.pb.go
  test/integration/components/testserver/grpc/server/server.go
  test/integration/components/testserver/testserver.go
  test/integration/docker-compose.yml
  test/integration/red_test.go
  test/integration/suites_test.go
Labels: enhancement

#51 Fix gRPC status tracking
  bpf/go_nethttp.c
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
Labels: bug

#50 Track HTTP request content length
  bpf/go_nethttp.c
  configs/offsets/tracker_input.json
  pkg/ebpf/nethttp/bpf_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/export/debug/debug.go
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/goexec/offsets.json
  pkg/goexec/structmembers.go
  pkg/pipe/instrumenter_test.go
  pkg/transform/spanner.go
  test/integration/red_test.go
Labels: enhancement

#56 Fix null termination bug
  bpf/go_str.h
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.o
Labels: bug

#64 Add trace event batching
  pkg/export/otel/traces.go
  pkg/pipe/instrumenter_test.go
Labels: enhancement

#73 Match on process suffix instead of contains
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.o
  pkg/goexec/file.go
Labels: bug

#75 Improve instrumenter logging
  pkg/ebpf/nethttp/nethttp.go
  pkg/goexec/offsets.go
  pkg/goexec/structmembers.go
Labels: enhancement

#74 Quickstart Tutorial + Fix endpoint handling
  .golangci.yml
  deployments/03-instrumented-app.yml
  docs/README.md
  docs/tutorial.md
  docs/tutorial/README.md
  docs/tutorial/img/avg-request-time.png
  docs/tutorial/img/dropdown-metrics.png
  docs/tutorial/img/grafana-instance-id.png
  docs/tutorial/server.go
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/pipe/instrumenter_test.go
  test/collector/collector.go
  test/integration/docker-compose.yml
Labels: bug, documentation, breaking-change

#76 Add more events to Prometheus to ensure visibility
  test/integration/red_test.go
Labels: bug

#80 Traces server span and url fixes
  pkg/export/otel/metrics.go
  pkg/export/otel/metrics_test.go
  pkg/export/otel/traces.go
  pkg/export/otel/traces_test.go
  pkg/pipe/instrumenter_test.go
  test/collector/collector.go
Labels: bug

#82 Add support for keepalive request time
  bpf/go_nethttp.c
  pkg/ebpf/nethttp/bpf_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.o
  pkg/ebpf/nethttp/nethttp.go
  pkg/pipe/config.go
  pkg/pipe/config_test.go
  pkg/pipe/instrumenter.go
  test/cmd/pingserver/debug.sh
  test/cmd/pingserver/driver.sh
Labels: enhancement
