Repository grafana/beyla, pull requests merged in 2023-07, with the labels that each got.

#175 Add .net TLS support and tests
  pkg/ebpf/httpfltr/httpfltr.go
  test/integration/components/dotnetserver/Dockerfile_tls
  test/integration/docker-compose-dotnet.yml
  test/integration/red_test_dotnet.go
  test/integration/suites_test.go
Labels: enhancement, test

#192 Support GRPC for OTEL_EXPORTER_OTLP_METRICS_PROTOCOL and set http/protobuf as default
  docs/sources/config/index.md
  go.mod
  go.sum
  pkg/export/otel/metrics.go
  pkg/export/otel/metrics_test.go
  pkg/export/otel/traces.go
  pkg/export/otel/traces_test.go
  pkg/pipe/config.go
  pkg/pipe/config_test.go
  test/integration/configs/instrumenter-config-grpc-export.yml
  test/integration/red_test.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/LICENSE
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/client.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/config.go
  vendor/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc/doc.go
  vendor/modules.txt
Labels: breaking-change

#194 Check and warn on insufficient permissions during process discovery
  pkg/ebpf/tracer.go
  pkg/exec/file.go
Labels: enhancement

#205 Read the statusCode on WriteHeader
  bpf/go_nethttp.c
  bpf/go_nethttp.h
  bpf/go_runtime.c
  bpf/http_ssl.h
  configs/offsets/tracker_input.json
  pkg/ebpf/goruntime/bpf_bpfel_arm64.o
  pkg/ebpf/goruntime/bpf_bpfel_x86.o
  pkg/ebpf/goruntime/bpf_debug_bpfel_arm64.o
  pkg/ebpf/goruntime/bpf_debug_bpfel_x86.o
  pkg/ebpf/httpfltr/bpf_bpfel_arm64.o
  pkg/ebpf/httpfltr/bpf_bpfel_x86.o
  pkg/ebpf/httpfltr/bpf_debug_bpfel_arm64.o
  pkg/ebpf/httpfltr/bpf_debug_bpfel_x86.o
  pkg/ebpf/nethttp/bpf_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.go
  pkg/ebpf/nethttp/bpf_debug_bpfel_arm64.o
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.go
  pkg/ebpf/nethttp/bpf_debug_bpfel_x86.o
  pkg/ebpf/nethttp/nethttp.go
  pkg/goexec/offsets.json
  pkg/goexec/structmembers.go
  pkg/goexec/structmembers_test.go
  test/integration/docker-compose.yml
  test/integration/red_test.go
  test/integration/red_test_dotnet.go
  test/integration/suites_test.go
Labels: bug

#215 Add debugging info for net TLS
  .gitignore
  bpf/http_sock.c
  bpf/http_ssl.h
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/httpfltr/httpfltr_test.go
  test/integration/components/beyla/Dockerfile_dbg
  test/integration/components/beyla/beyla_wrapper.sh
  test/integration/docker-compose-dotnet.yml
  test/integration/red_test_dotnet.go
  test/integration/suites_test.go
Labels: test
