Repository grafana/beyla, pull requests merged in 2024-11, with the labels that each got.

#1316 Add Formatting to Variable Name
  docs/sources/configure/options.md
Labels: missing-labels, backport, backport release-1.6, backport release-1.5, backport-release-1.7, backport-release-1.8

#1387 Fix environment variable name for configuring otel traces features
  docs/sources/configure/options.md
Labels: backport-1.6, backport release-1.6, backport-release-1.7, backport-1.7, backport-1.8, backport-release-1.8, missing-labels

#1415 Align Beyla setting Service Name/Namespace/Instance according to OTEL collector
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/components/beyla.go
  pkg/internal/discover/watcher_kube_test.go
  pkg/internal/kube/informer_provider.go
  pkg/internal/kube/store.go
  pkg/internal/kube/store_test.go
  pkg/kubecache/informer/informer.pb.go
  pkg/kubecache/meta/informers_init.go
  pkg/transform/k8s.go
  pkg/transform/k8s_test.go
  pkg/transform/name_resolver_test.go
  proto/informer.proto
  test/integration/k8s/daemonset/k8s_daemonset_traces_test.go
  test/integration/k8s/daemonset_multi_node/k8s_daemonset_multi_node_traces_test.go
  test/integration/k8s/daemonset_multi_node_l7/k8s_daemonset_multi_node_traces_test.go
  test/integration/k8s/daemonset_python/k8s_daemonset_traces_test.go
  test/integration/k8s/informer_cache/k8s_informer_cache_main_test.go
  test/integration/k8s/manifests/05-uninstrumented-service-python.yml
  test/integration/k8s/manifests/05-uninstrumented-service.yml
  test/integration/k8s/manifests/06-beyla-external-informer.yml
  test/integration/k8s/owners/k8s_daemonset_metadata_test.go
  test/integration/k8s/owners/k8s_statefulset_metadata_test.go
Labels: breaking-change, 2.0
