Repository grafana/beyla, pull requests merged in 2024-07, with the labels that each got.

#989 enable by default: server_address and server_port attributes
  pkg/internal/export/attributes/attr_defs.go
Labels: breaking-change

#988 Set heuristic as default value for unmatched routes arg
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
Labels: breaking-change

#997 Allow to selectively disable some K8s informers
  pkg/components/beyla.go
  pkg/internal/kube/informer.go
  pkg/internal/kube/informer_ip.go
  pkg/internal/kube/informer_provider.go
  pkg/internal/kube/informer_type.go
  pkg/internal/kube/informer_type_test.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/transform/k8s.go
  test/integration/k8s/common/k8s_metrics_testfuncs.go
  test/integration/k8s/disable_informers/k8s_disable_informers_test.go
  test/integration/k8s/manifests/06-beyla-daemonset-disable-informers.yml
Labels: ready-for-review

#996 Document wildcards in attributes.select
  docs/sources/configure/options.md
Labels: documentation

#1012 Avoid un-understandable Pipes panics
  cmd/beyla/main.go
  pkg/components/beyla.go
  pkg/components/beyla_test.go
Labels: bug

#1022 remove client.address as default attribute on RPC metrics
  pkg/internal/export/attributes/attr_defs.go
  pkg/internal/pipe/instrumenter_test.go
Labels: bug

#1020 Docs: enumerate client/server port and process metrics
  docs/sources/configure/options.md
  docs/sources/metrics.md
Labels: documentation

#1038 Export k8s flags
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/internal/kube/informer_provider.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/kubeflags/kubeflags.go
  pkg/transform/k8s.go
Labels: 1.8.0

#1051 Link directly to resource in GitHub
  docs/sources/configure/export-modes.md
  docs/sources/tutorial/getting-started.md
Labels: documentation, type/docs
