Repository grafana/beyla, pull requests merged in 2024-05, with the labels that each got.

#789 App metrics attribute selectors
  docs/sources/network/quickstart.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/components/beyla.go
  pkg/internal/export/attr/allowed.go
  pkg/internal/export/attr/allowed_test.go
  pkg/internal/export/attr/attr.go
  pkg/internal/export/metric/attr/attrs.go
  pkg/internal/export/metric/attr_defs.go
  pkg/internal/export/metric/attr_defs_test.go
  pkg/internal/export/metric/attr_getters.go
  pkg/internal/export/metric/attr_select.go
  pkg/internal/export/metric/attr_selector.go
  pkg/internal/export/metric/attr_selector_test.go
  pkg/internal/export/metric/metric.go
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/export/prom/prom.go
  pkg/internal/helpers/maps.go
  pkg/internal/helpers/maps_test.go
  pkg/internal/kube/owner.go
  pkg/internal/metricname/metricname.go
  pkg/internal/netolly/agent/pipeline.go
  pkg/internal/netolly/ebpf/record.go
  pkg/internal/netolly/ebpf/record_getters.go
  pkg/internal/netolly/export/attributes.go
  pkg/internal/netolly/export/otel/expirer.go
  pkg/internal/netolly/export/otel/expirer_test.go
  pkg/internal/netolly/export/otel/metrics.go
  pkg/internal/netolly/export/otel/metrics_test.go
  pkg/internal/netolly/export/printer.go
  pkg/internal/netolly/export/prom/expirer.go
  pkg/internal/netolly/export/prom/expirer_test.go
  pkg/internal/netolly/export/prom/prom.go
  pkg/internal/netolly/transform/cidr/cidr.go
  pkg/internal/netolly/transform/k8s/kubernetes.go
  pkg/internal/pipe/global/context.go
  pkg/internal/pipe/instrumenter.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/request/metric_attributes.go
  pkg/internal/request/span.go
  pkg/internal/request/span_getters.go
  pkg/internal/svc/svc.go
  pkg/transform/k8s.go
  pkg/transform/k8s_test.go
  pkg/transform/name_resolver.go
  pkg/transform/name_resolver_test.go
  test/collector/collector.go
  test/integration/configs/instrumenter-config-netolly-disallowattrs.yml
  test/integration/configs/instrumenter-config-netolly.yml
  test/integration/k8s/manifests/06-beyla-netolly-dropexternal.yml
  test/integration/k8s/manifests/06-beyla-netolly-promexport.yml
  test/integration/k8s/manifests/06-beyla-netolly-sk-promexport.yml
  test/integration/k8s/manifests/06-beyla-netolly.yml
Labels: ready-for-review

#808 Fix crash if only application_service_graph feature is enabled (1.5 b…
  pkg/internal/export/otel/metrics.go
Labels: backport-1.5

#839 Add backup path for finishing requests
  bpf/http_sock.c
  bpf/http_sock.h
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/internal/ebpf/common/common.go
  pkg/internal/ebpf/common/httpfltr_transform.go
  pkg/internal/ebpf/httpfltr/bpf_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_tp_bpfel_x86-6d31b434.o.tmp
  pkg/internal/ebpf/httpfltr/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/httpfltr.go
  pkg/internal/ebpf/httpssl/bpf_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_bpfel_x86.o
  pkg/internal/export/expire/clock.go
  test/integration/components/pythonserver/Dockerfile
  test/integration/components/pythonserver/main.py
  test/integration/docker-compose-python.yml
  test/integration/red_test_python.go
  test/integration/suites_test.go
  test/integration/test_utils.go
Labels: enhancement

#828 OATS tests coverage report
  .github/workflows/pull_request_oats_test.yml
  Makefile
  test/oats/sql/docker-compose-beyla-gosqlclient.yml
  test/oats/sql_other_langs/docker-compose-beyla-sql.yml
  test/oats/sql_statement/docker-compose-beyla-gosqlclient.yml
Labels: ready-for-review

#843 Document attributes selection and filtering features
  devdocs/pipeline-map.md
  docs/sources/configure/options.md
  docs/sources/flowchart/architecture.mmd
  docs/sources/metrics.md
  pkg/internal/export/attributes/attr_select.go
Labels: type/docs

#863 Fix attributes filter network documentation (1.6 backport)
  docs/sources/network/_index.md
  docs/sources/network/config.md
  docs/sources/network/quickstart.md
  pkg/beyla/config_test.go
Labels: type/docs, backport-1.6

#866 Updating image version in documentation
  docs/sources/tutorial/k8s-walkthrough.md
Labels: backport-1.6

#889 [1.6] Fix HTTP parsing for duplicate responses
  bpf/http_sock.h
  pkg/internal/ebpf/httpfltr/bpf_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_bpfel_x86.o
Labels: backport-1.6
