Repository grafana/beyla, pull requests merged in 2024-12, with the labels that each got.

#1424 Fix informers on stale object deletion [1.9 backport]
  pkg/kubecache/meta/informers_init.go
Labels: backport-1.9

#1431 Correct documentation of routes default behavior
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/transform/routes.go
Labels: backport, backport-release-1.8, backport release-1.9, backport-release-1.9, type/docs

#1432 Fix eBPF Instruction Set broken url
  docs/sources/_index.md
Labels: backport-release-1.9

#1440 allow restricting Kube metadata to local node only
  .github/workflows/pull_request_integration_tests.yml
  .github/workflows/pull_request_k8s_integration_tests.yml
  docs/sources/configure/options.md
  pkg/components/beyla.go
  pkg/internal/kube/informer_provider.go
  pkg/kubecache/meta/informers_init.go
  pkg/transform/k8s.go
  test/integration/k8s/manifests/02-prometheus-otelscrape.yml
  test/integration/k8s/manifests/05-uninstrumented-server-client-different-nodes.yml
  test/integration/k8s/manifests/06-beyla-netolly.yml
  test/integration/k8s/netolly_promexport/k8s_netolly_prom_main_test.go
  test/integration/k8s/restrict_local_node/restrict_local_node_main_test.go
Labels: backport release-1.9, product-approved

#1476 Treat go binaries without offsets as generic
  pkg/internal/discover/attacher.go
  pkg/internal/discover/typer.go
  pkg/internal/goexec/structmembers.go
Labels: type/bug

#1477 Treat go binaries without offsets as generic (1.9 branch patch)
  pkg/internal/discover/attacher.go
  pkg/internal/discover/typer.go
  pkg/internal/goexec/structmembers.go
Labels: type/bug
