Repository grafana/beyla, pull requests merged in 2024-08, with the labels that each got.

#1079 Update ClusterRole permissions in documentation
  docs/sources/setup/kubernetes.md
  docs/sources/tutorial/k8s-walkthrough.md
Labels: type/docs, backport-release-1.7, backport-1.7

#1082 Update ClusterRole permissions in documentation [1.7 backport]
  docs/sources/setup/kubernetes.md
  docs/sources/tutorial/k8s-walkthrough.md
Labels: backport-1.7

#1067 Check if required capabilities are available
  cmd/beyla/main.go
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/beyla/os.go
  pkg/beyla/os_test.go
  pkg/internal/discover/attacher_linux.go
  pkg/internal/ebpf/common/common.go
  pkg/internal/ebpf/grpc/grpc.go
  pkg/internal/ebpf/nethttp/nethttp.go
  pkg/internal/helpers/capabilities.go
  pkg/internal/helpers/capabilities_linux_privilieged_test.go
  pkg/internal/helpers/capabilities_test.go
  test/integration/docker-compose-client.yml
Labels: type/docs

#1108 Split iovec reading for tcp_recvmsg
  bpf/http_sock.c
  bpf/protocol_common.h
  pkg/internal/ebpf/httpfltr/bpf_arm64_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_arm64_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_debug_arm64_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_debug_x86_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_tp_arm64_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_arm64_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_x86_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_tp_x86_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/httpfltr/bpf_x86_bpfel.go
  pkg/internal/ebpf/httpfltr/bpf_x86_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_arm64_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/httpssl/bpf_x86_bpfel.o
Labels: wip

#1110 Renaming process.cpu.state attribute to cpu.mode
  pkg/export/attributes/attr_defs.go
  pkg/export/attributes/names/attrs.go
  pkg/export/otel/expirer.go
  pkg/export/otel/metrics_proc.go
  pkg/export/otel/metrics_proc_test.go
  pkg/export/prom/prom_proc.go
  pkg/export/prom/prom_proc_test.go
  pkg/internal/infraolly/process/status.go
  test/integration/configs/instrumenter-config-java.yml
  test/integration/configs/instrumenter-config-promscrape.yml
Labels: breaking-change

#1119 Rename beyla_build_info for internal registry
  docs/sources/metrics.md
  grafana/beyla.json
  pkg/internal/imetrics/iprom.go
Labels: breaking-change
