Repository grafana/beyla, pull requests merged in 2024-06, with the labels that each got.

#906 check kafka pkt length before parsing clientid
  pkg/internal/ebpf/common/kafka_detect_transform.go
Labels: bug

#941 Use proper pre/suffixes for internal metrics names
  docs/sources/metrics.md
  pkg/internal/imetrics/iprom.go
  test/integration/internals_test.go
Labels: breaking-change

#947 Fix link in options.md
  docs/sources/configure/options.md
Labels: backport-1.6

#952 Fix OTEL traces URL endpoint
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
Labels: bug

#953 Fix OTEL traces URL endpoint [1.6 backport]
  pkg/internal/export/otel/common.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
Labels: bug, backport-1.6

#964 Fix typo in BPF debug yaml field
  pkg/internal/ebpf/common/common.go
Labels: breaking-change

#968 App metrics/traces: decorate peer service IPs with service names
  pkg/internal/kube/informer_ip.go
  pkg/internal/transform/kube/db.go
  pkg/transform/k8s.go
  pkg/transform/k8s_test.go
  pkg/transform/name_resolver.go
  test/integration/k8s/common/k8s_metrics_testfuncs.go
Labels: bug

#967 Improve .NET language detection
  pkg/internal/exec/proclang.go
  pkg/internal/exec/proclang_linux.go
  pkg/internal/exec/proclang_test.go
Labels: bug
