Repository grafana/beyla, pull requests merged in 2024-09, with the labels that each got.

#1118 Improving thread safety of K8s informer DB
  pkg/internal/transform/kube/db.go
Labels: bug

#1123 Prevent negative network tx/rx data for process
  pkg/internal/infraolly/process/harvest.go
Labels: bug

#1125 Cleanup UID/InstanceID duplicity. Also remove `override_instance_id` config option
  docs/sources/configure/options.md
  pkg/export/otel/common.go
  pkg/export/otel/metrics.go
  pkg/export/prom/prom.go
  pkg/internal/request/span_getters.go
  pkg/internal/svc/svc.go
  pkg/internal/traces/read_decorator.go
  pkg/internal/traces/read_decorator_test.go
  pkg/transform/k8s.go
Labels: breaking-change

#1129 Deduplicate instance ids and restore target_instance in Prometheus
  pkg/export/attributes/attr_defs.go
  pkg/export/otel/metrics_proc.go
  pkg/internal/infraolly/process/status.go
  pkg/internal/request/span_getters.go
  pkg/internal/svc/svc.go
  pkg/internal/svc/uid.go
  pkg/internal/svc/uid_test.go
  pkg/internal/traces/read_decorator.go
  pkg/internal/traces/read_decorator_test.go
  pkg/transform/k8s.go
  test/integration/red_test_rust.go
  test/integration/traces_test.go
Labels: bug

#1141 Docs: Fix link to 'Beyla and Kubernetes walkthrough'
  docs/sources/tutorial/helm-alloy.md
Labels: documentation

#1157 Avoid that a Pod update removes the container metadata #1156
  pkg/internal/transform/kube/db.go
Labels: bug, backport-release-1.8

#1175 Support for RHEL 4.18 kernels
  README.md
  docs/sources/_index.md
  pkg/beyla/os.go
  pkg/beyla/os_test.go
  pkg/internal/ebpf/instrumenter.go
  pkg/internal/ebpf/ktracer/ktracer.go
  test/integration/multiprocess_test.go
  test/integration/red_test_nodeclient.go
  test/integration/red_test_rust.go
  test/integration/suites_test.go
  test/integration/traces_test.go
Labels: documentation

#1188 Add quickstart build instructions to the README file
  README.md
Labels: documentation
