Repository grafana/beyla, pull requests merged in 2024-02, with the labels that each got.

#598 Update metric collection names to stable HTTP spec
  docs/sources/configure/options.md
  docs/sources/metrics.md
  grafana/dashboard.json
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/prom/prom.go
  pkg/internal/pipe/instrumenter_test.go
  test/integration/http2go_test.go
  test/integration/k8s/common/k8s_metrics_testfuncs.go
  test/integration/multiprocess_test.go
  test/integration/red_test.go
  test/integration/red_test_client.go
  test/integration/red_test_dotnet.go
  test/integration/red_test_java.go
  test/integration/red_test_nodeclient.go
  test/integration/red_test_nodejs.go
  test/integration/red_test_python.go
  test/integration/red_test_ruby.go
  test/integration/red_test_rust.go
  test/integration/test_utils.go
Labels: breaking-change

#611 Add docs for running unprivileged in k8s
  docs/sources/configure/export-modes.md
  docs/sources/configure/options.md
  docs/sources/distributed-traces.md
  docs/sources/quickstart/_index.md
  docs/sources/quickstart/java.md
  docs/sources/quickstart/rust.md
  docs/sources/setup/kubernetes.md
  docs/sources/tutorial/getting-started.md
  docs/sources/tutorial/k8s-walkthrough.md
  examples/k8s/unprivileged.yaml
Labels: documentation

#636 Fix docs links and build warnings
  docs/sources/configure/export-modes.md
  docs/sources/quickstart/_index.md
  docs/sources/quickstart/cpp.md
  docs/sources/quickstart/golang.md
  docs/sources/quickstart/java.md
  docs/sources/quickstart/nodejs.md
  docs/sources/quickstart/python.md
  docs/sources/quickstart/ruby.md
  docs/sources/quickstart/rust.md
  docs/sources/requesttime.md
  docs/sources/tutorial/getting-started.md
Labels: backport-1.0, backport-1.2, backport release-1.2, type/docs, backport
