Repository grafana/beyla, pull requests merged in 2024-10, with the labels that each got.

#1225 Fixes process metrics when the application has not sent/received any request
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/export/prom/expirer.go
  pkg/export/prom/prom.go
  pkg/internal/appolly/appolly.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/finder.go
  pkg/internal/infraolly/process/collect.go
  pkg/internal/request/span.go
  test/integration/configs/prometheus-config-promscrape-k8s-test.yml
  test/integration/docker-compose-python.yml
  test/integration/k8s/manifests/06-beyla-all-processes.yml
  test/integration/k8s/process_notraces/k8s_process_notraces_test.go
  test/integration/suites_test.go
Labels: bug

#1236 Fixes process metrics when the application has not sent/received any request
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/export/prom/expirer.go
  pkg/export/prom/prom.go
  pkg/internal/appolly/appolly.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/finder.go
  pkg/internal/infraolly/process/collect.go
  pkg/internal/request/span.go
  test/integration/configs/prometheus-config-promscrape-k8s-test.yml
  test/integration/docker-compose-python.yml
  test/integration/k8s/manifests/06-beyla-all-processes.yml
  test/integration/k8s/process_notraces/k8s_process_notraces_test.go
  test/integration/process_test.go
  test/integration/suites_test.go
Labels: backport-1.8

#1251 Share bpf maps internally and remove pinning / bpffs requirement
  bpf/bpf_dbg.h
  bpf/go_common.h
  bpf/http_ssl_defs.h
  bpf/k_tracer.h
  bpf/nodejs.h
  bpf/pid.h
  bpf/pin_internal.h
  bpf/protocol_common.h
  bpf/protocol_http.h
  bpf/protocol_http2.h
  bpf/protocol_tcp.h
  bpf/ringbuf.h
  bpf/trace_common.h
  bpf/tracing.h
  docs/sources/setup/kubernetes.md
  examples/k8s/unprivileged.yaml
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/config/ebpf_tracer.go
  pkg/internal/appolly/appolly.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/attacher_linux.go
  pkg/internal/discover/attacher_linux_privileged_test.go
  pkg/internal/discover/attacher_nolinux.go
  pkg/internal/discover/mountinfo_linux.go
  pkg/internal/discover/mountinfo_linux_test.go
  pkg/internal/discover/watcher_proc.go
  pkg/internal/ebpf/generictracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/logger/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/logger/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/tracer.go
  pkg/internal/ebpf/tracer_darwin.go
  pkg/internal/ebpf/tracer_linux.go
  pkg/internal/ebpf/watcher/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/watcher/bpf_debug_x86_bpfel.o
Labels: documentation

#1259 Docs information architecture refactor pass 1
  docs/sources/_index.md
  docs/sources/beyla-dashboard.md
  docs/sources/configure/_index.md
  docs/sources/configure/export-modes.md
  docs/sources/distributed-traces.md
  docs/sources/metrics.md
  docs/sources/network/_index.md
  docs/sources/quickstart/_index.md
  docs/sources/quickstart/kubernetes.md
  docs/sources/requesttime.md
  docs/sources/setup/_index.md
  docs/sources/setup/docker.md
  docs/sources/setup/helm-alloy.md
  docs/sources/setup/kubernetes-helm.md
  docs/sources/setup/kubernetes.md
  docs/sources/setup/standalone.md
  docs/sources/stability.md
  docs/sources/tutorial/_index.md
  docs/sources/tutorial/getting-started.md
  docs/sources/tutorial/resources/server.go
Labels: documentation, enhancement

#1266 Enabling external informer
  go.mod
  go.sum
  pkg/components/beyla.go
  pkg/internal/discover/watcher_kube.go
  pkg/internal/discover/watcher_kube_test.go
  pkg/internal/ebpf/tctracer/tctracer_notlinux.go
  pkg/internal/kube/cache_svc_client.go
  pkg/internal/kube/informer_provider.go
  pkg/internal/kube/store.go
  pkg/internal/pipe/global/host_id.go
  pkg/transform/k8s.go
  pkg/transform/k8s_test.go
  test/integration/k8s/common/k8s_metrics_testfuncs.go
  test/integration/k8s/informer_cache/k8s_informer_cache_main_test.go
  test/integration/k8s/manifests/05-uninstrumented-service.yml
  test/integration/k8s/manifests/06-beyla-external-informer.yml
  test/integration/k8s/netolly/k8s_netolly_network_metrics.go
  test/integration/k8s/otel/k8s_otel_metrics_test.go
  test/integration/k8s/prom/k8s_prom_test.go
  vendor/github.com/grafana/beyla-k8s-cache/NOTICE
  vendor/github.com/grafana/beyla-k8s-cache/pkg/informer/informer.pb.go
  vendor/github.com/grafana/beyla-k8s-cache/pkg/informer/informer_grpc.pb.go
  vendor/github.com/grafana/beyla-k8s-cache/pkg/meta/informers_init.go
  vendor/modules.txt
Labels: bug, enhancement

#1271 Replace drone by github actions for image publishing
  .drone/drone.jsonnet
  .drone/drone.yml
  .github/workflows/publish_dockerhub_main.yml
  .github/workflows/publish_dockerhub_release.yml
  .github/workflows/pull_request.yml
  Makefile
  README.md
  scripts/check-drone-drift.sh
Labels: bug

#1276 Fix wrong language detection
  pkg/internal/discover/attacher.go
Labels: bug

#1287 Fixes cgroup ID parsing in newer docker versions
  pkg/internal/helpers/container/container.go
  pkg/internal/helpers/container/container_test.go
Labels: bug

#1288 Typo in docs
  docs/sources/setup/helm-alloy.md
Labels: backport-1.5, backport-1.6, backport-1.7, backport-1.8
