Repository grafana/beyla, pull requests merged in 2024-03, with the labels that each got.

#663 Make sure that all the subcomponents have finished before stopping Beyla
  cmd/beyla/main.go
  pkg/components/beyla.go
Labels: bug

#664 Docs: Update Docker instructions
  docs/sources/setup/docker.md
Labels: backport-1.2, backport-1.3

#681 Fix internal metrics documentation section
  docs/sources/configure/options.md
Labels: backport-1.3
