Repository grafana/beyla, pull requests merged in 2024-04, with the labels that each got.

#674 Update Go version to 1.22 + update and fix linters
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_integration_tests.yml
  .github/workflows/pull_request_oats_test.yml
  .github/workflows/release-binaries.yml
  .github/workflows/update-offsets.yml
  .golangci.yml
  Dockerfile
  Makefile
  cmd/beyla/main.go
  generator.Dockerfile
  go.mod
  pkg/internal/discover/watcher_proc_test.go
  pkg/internal/ebpf/common/common.go
  pkg/internal/ebpf/common/http2grpc_transform.go
  pkg/internal/ebpf/common/pids.go
  pkg/internal/ebpf/common/spanner_test.go
  pkg/internal/ebpf/tracer_linux.go
  pkg/internal/export/grafana_agent/traces.go
  pkg/internal/netolly/export/attributes.go
  pkg/internal/netolly/ifaces/registerer_test.go
  pkg/internal/netolly/ifaces/watcher_test.go
  pkg/internal/sqlprune/sqlparser.go
  pkg/internal/traces/hostname/hostname_test.go
  pkg/transform/k8s.go
  test/cmd/grpc/client/client.go
  test/cmd/pingserver/server.go
  test/cmd/pingwrapper/wrapper.go
  test/integration/close_test.go
  test/integration/components/beyla/Dockerfile
  test/integration/components/beyla/Dockerfile_dbg
  test/integration/components/gohttp2/client/Dockerfile
  test/integration/components/gohttp2/client/go.mod
  test/integration/components/gohttp2/server/Dockerfile
  test/integration/components/gohttp2/server/go.mod
  test/integration/components/grpcpinger/Dockerfile
  test/integration/components/kube/kind.go
  test/integration/components/pingclient/Dockerfile
  test/integration/components/sqlclient/Dockerfile
  test/integration/components/testserver/Dockerfile
  test/integration/components/testserver/Dockerfile_duplicate
  test/integration/components/testserver/Dockerfile_nodebug
  test/integration/components/testserver/Dockerfile_rename1
  test/integration/components/testserver/Dockerfile_static
  test/integration/components/testserver/grpc/client/client.go
  test/integration/k8s/common/k8s_metrics_testfuncs.go
  test/integration/k8s/daemonset/k8s_daemonset_traces_test.go
  test/integration/k8s/daemonset_python/k8s_daemonset_traces_test.go
  test/integration/k8s/manifests/06-instrumented-client.template.yml
  test/integration/k8s/manifests/06-uninstrumented-client.template.yml
  test/integration/k8s/otel/k8s_otel_traces_test.go
  test/integration/k8s/owners/k8s_daemonset_metadata_test.go
  test/integration/k8s/owners/k8s_statefulset_metadata_test.go
  test/integration/suites_test.go
  test/oats/go.mod
Labels: do-not-merge

#736 Updated the pipes library
  go.mod
  go.sum
  pkg/internal/appolly/appolly.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/container_updater.go
  pkg/internal/discover/finder.go
  pkg/internal/discover/matcher.go
  pkg/internal/discover/matcher_test.go
  pkg/internal/discover/typer.go
  pkg/internal/discover/watcher_kube.go
  pkg/internal/discover/watcher_kube_test.go
  pkg/internal/discover/watcher_proc.go
  pkg/internal/export/alloy/traces.go
  pkg/internal/export/debug/debug.go
  pkg/internal/export/otel/metrics.go
  pkg/internal/export/otel/metrics_test.go
  pkg/internal/export/otel/traces.go
  pkg/internal/export/otel/traces_test.go
  pkg/internal/export/prom/prom.go
  pkg/internal/netolly/agent/agent.go
  pkg/internal/netolly/agent/pipeline.go
  pkg/internal/netolly/ebpf/sock_tracer_nolinux.go
  pkg/internal/netolly/export/otel/metrics.go
  pkg/internal/netolly/export/printer.go
  pkg/internal/netolly/export/prom/expirer_test.go
  pkg/internal/netolly/export/prom/prom.go
  pkg/internal/netolly/flow/deduper.go
  pkg/internal/netolly/flow/deduper_test.go
  pkg/internal/netolly/flow/reverse_dns.go
  pkg/internal/netolly/flow/reverse_dns_test.go
  pkg/internal/netolly/flow/tracer_map.go
  pkg/internal/netolly/flow/tracer_ringbuf.go
  pkg/internal/netolly/transform/cidr/cidr.go
  pkg/internal/netolly/transform/k8s/kubernetes.go
  pkg/internal/pipe/instrumenter.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/traces/read_decorator.go
  pkg/internal/traces/read_decorator_test.go
  pkg/transform/k8s.go
  pkg/transform/routes.go
  pkg/transform/routes_test.go
  third_party_licenses.csv
  vendor/github.com/mariomac/pipes/pipe/builder.go
  vendor/github.com/mariomac/pipes/pipe/bypass.go
  vendor/github.com/mariomac/pipes/pipe/internal/connect/connectors.go
  vendor/github.com/mariomac/pipes/pipe/node.go
  vendor/github.com/mariomac/pipes/pipe/options.go
  vendor/github.com/mariomac/pipes/pipe/providers.go
  vendor/github.com/mariomac/pipes/pipe/runner.go
  vendor/github.com/mariomac/pipes/pkg/graph/builder.go
  vendor/github.com/mariomac/pipes/pkg/graph/config.go
  vendor/github.com/mariomac/pipes/pkg/graph/connector.go
  vendor/github.com/mariomac/pipes/pkg/graph/graph.go
  vendor/github.com/mariomac/pipes/pkg/graph/grdemux.go
  vendor/github.com/mariomac/pipes/pkg/graph/stage/stage.go
  vendor/github.com/mariomac/pipes/pkg/node/demux.go
  vendor/github.com/mariomac/pipes/pkg/node/node.go
  vendor/modules.txt
Labels: enhancement

#751 Fix Go http/grpc bad data
  bpf/go_grpc.c
  bpf/go_nethttp.c
  bpf/go_nethttp.h
  pkg/internal/ebpf/common/ringbuf.go
  pkg/internal/ebpf/grpc/bpf_bpfel_arm64.o
  pkg/internal/ebpf/grpc/bpf_bpfel_x86.o
  pkg/internal/ebpf/grpc/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/grpc/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/grpc/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/grpc/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/grpc/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/grpc/bpf_tp_debug_bpfel_x86.o
  pkg/internal/ebpf/nethttp/bpf_bpfel_arm64.go
  pkg/internal/ebpf/nethttp/bpf_bpfel_arm64.o
  pkg/internal/ebpf/nethttp/bpf_bpfel_x86.go
  pkg/internal/ebpf/nethttp/bpf_bpfel_x86.o
  pkg/internal/ebpf/nethttp/bpf_debug_bpfel_arm64.go
  pkg/internal/ebpf/nethttp/bpf_debug_bpfel_arm64.o
  pkg/internal/ebpf/nethttp/bpf_debug_bpfel_x86.go
  pkg/internal/ebpf/nethttp/bpf_debug_bpfel_x86.o
  pkg/internal/ebpf/nethttp/bpf_tp_bpfel_arm64.go
  pkg/internal/ebpf/nethttp/bpf_tp_bpfel_arm64.o
  pkg/internal/ebpf/nethttp/bpf_tp_bpfel_x86.go
  pkg/internal/ebpf/nethttp/bpf_tp_bpfel_x86.o
  pkg/internal/ebpf/nethttp/bpf_tp_debug_bpfel_arm64.go
  pkg/internal/ebpf/nethttp/bpf_tp_debug_bpfel_arm64.o
  pkg/internal/ebpf/nethttp/bpf_tp_debug_bpfel_x86.go
  pkg/internal/ebpf/nethttp/bpf_tp_debug_bpfel_x86.o
  pkg/internal/ebpf/nethttp/nethttp.go
  pkg/internal/goexec/structmembers.go
  pkg/internal/goexec/structmembers_test.go
  pkg/internal/request/span.go
Labels: bug

#777 remove network.allowed_attributes and use attributes.allow.<metric name>
  docs/sources/network/config.md
  docs/sources/network/quickstart.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/beyla/network_cfg.go
  pkg/internal/export/attr/allowed.go
  pkg/internal/export/attr/allowed_test.go
  pkg/internal/export/attr/attr.go
  pkg/internal/metricname/metricname.go
  pkg/internal/netolly/agent/pipeline.go
  pkg/internal/netolly/export/attributes.go
  pkg/internal/netolly/export/otel/metrics.go
  pkg/internal/netolly/export/prom/prom.go
  test/integration/configs/instrumenter-config-netolly-disallowattrs.yml
  test/integration/configs/instrumenter-config-netolly.yml
  test/integration/docker-compose-netolly.yml
  test/integration/k8s/manifests/06-beyla-netolly-dropexternal.yml
  test/integration/k8s/manifests/06-beyla-netolly-promexport.yml
  test/integration/k8s/manifests/06-beyla-netolly-sk-promexport.yml
  test/integration/k8s/manifests/06-beyla-netolly.yml
  test/integration/suites_network_test.go
Labels: breaking-change

#790 Add extra k8s docs explanations
  docs/sources/setup/kubernetes.md
  examples/k8s/unprivileged.yaml
Labels: documentation
