Repository grafana/beyla, pull requests merged in 2025-05, with the labels that each got.

#1875 Change how we correlate SSL to connection information
  bpf/common/runtime.h
  bpf/common/sockaddr.h
  bpf/common/ssl_args.h
  bpf/common/ssl_helpers.h
  bpf/common/trace_common.h
  bpf/generictracer/generictracer.c
  bpf/generictracer/k_tracer.c
  bpf/generictracer/libssl.c
  bpf/generictracer/protocol_http.h
  bpf/generictracer/protocol_tcp.h
  bpf/generictracer/ssl_defs.h
  bpf/tpinjector/tpinjector.c
  test/integration/components/pythonredis/main.py
Labels: port-to-otel-ebpf-inst

#1899 Fix tracking stale requests
  bpf/common/trace_common.h
  bpf/generictracer/protocol_http.h
  bpf/generictracer/protocol_tcp.h
Labels: port-to-otel-ebpf-inst

#1907 Remove PID to prevent cardinality explosion
  pkg/export/alloy/traces_test.go
  pkg/export/otel/common.go
  pkg/export/otel/metrics.go
  pkg/export/otel/traces_test.go
  pkg/export/prom/prom.go
  pkg/export/prom/prom_test.go
  pkg/internal/discover/typer.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/svc/svc.go
  pkg/internal/traces/read_decorator.go
  pkg/internal/traces/read_decorator_test.go
  test/integration/red_test_rust.go
  test/integration/traces_test.go
Labels: backport, port-to-otel-ebpf-inst

#1910 Revert the stripping of the PID in the svc.Instance
  pkg/internal/traces/read_decorator.go
  pkg/internal/traces/read_decorator_test.go
  test/integration/red_test_rust.go
  test/integration/traces_test.go
Labels: backport, port-to-otel-ebpf-inst

#1906 Introduce Required() method
  pkg/internal/discover/finder.go
  pkg/internal/ebpf/generictracer/generictracer.go
  pkg/internal/ebpf/generictracer/generictracer_notlinux.go
  pkg/internal/ebpf/gotracer/gotracer.go
  pkg/internal/ebpf/gpuevent/gpuevent.go
  pkg/internal/ebpf/httptracer/httptracer.go
  pkg/internal/ebpf/httptracer/httptracer_notlinux.go
  pkg/internal/ebpf/tctracer/tctracer.go
  pkg/internal/ebpf/tctracer/tctracer_notlinux.go
  pkg/internal/ebpf/tpinjector/tpinjector.go
  pkg/internal/ebpf/tpinjector/tpinjector_notlinux.go
  pkg/internal/ebpf/tracer.go
  pkg/internal/ebpf/tracer_linux.go
Labels: port-to-otel-ebpf-inst

#1914 Add bound checks to fastelf
  pkg/internal/exec/proclang_linux.go
  pkg/internal/fastelf/fastelf.go
  pkg/internal/fastelf/fastelf_test.go
Labels: backport, bug

#1918 Fix wrong SSL port
  bpf/common/ssl_helpers.h
  bpf/generictracer/k_tracer.c
  test/integration/traces_test.go
Labels: backport, bug, port-to-otel-ebpf-inst

#1917 Fix block in instrumentable discovery
  pkg/internal/appolly/appolly.go
  pkg/internal/appolly/appolly_test.go
Labels: backport, bug

#1950 Remove prototype L7 tracer
  bpf/httptracer/httptracer.c
  bpf/httptracer/placeholder.go
  bpf/imports.go
  pkg/beyla/os.go
  pkg/config/ebpf_tracer.go
  pkg/internal/discover/finder.go
  pkg/internal/ebpf/generictracer/generictracer.go
  pkg/internal/ebpf/httptracer/httptracer.go
  pkg/internal/ebpf/httptracer/httptracer_notlinux.go
  test/integration/docker-compose-multiexec-host.yml
  test/integration/docker-compose-multiexec.yml
  test/integration/k8s/daemonset_multi_node_l7/k8s_daemonset_multi_node_main_test.go
  test/integration/k8s/daemonset_multi_node_l7/k8s_daemonset_multi_node_traces_test.go
  test/integration/k8s/manifests/06-beyla-daemonset-multi-node-l7.yml
  test/integration/multiprocess_test.go
Labels: port-to-otel-ebpf-inst

#1939 Optimize k8s cache
  pkg/internal/helpers/sync/queue.go
  pkg/internal/helpers/sync/queue_test.go
  pkg/internal/kube/cache_svc_client.go
  pkg/internal/kube/cache_svc_client_test.go
  pkg/internal/kube/informer_provider.go
  pkg/kubecache/config.go
  pkg/kubecache/envtest/integration_test.go
  pkg/kubecache/informer/informer.pb.go
  pkg/kubecache/meta/informers.go
  pkg/kubecache/meta/informers_init.go
  pkg/kubecache/service/service.go
  proto/informer.proto
Labels: breaking-change, port-to-otel-ebpf-inst

#1965 Fix Go gRPC context propagation support
  bpf/gotracer/go_grpc.c
  bpf/gotracer/go_nethttp.c
  bpf/gotracer/go_offsets.h
  bpf/gotracer/go_stream_key.h
  configs/offsets/tracker_input.json
  pkg/internal/ebpf/gotracer/gotracer.go
  pkg/internal/goexec/offsets.json
  pkg/internal/goexec/structmembers.go
Labels: bug, port-to-otel-ebpf-inst

#1977 Prevent unnecessary K8s cache updates
  go.mod
  pkg/kubecache/meta/informers_init.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/google.golang.org/protobuf/internal/msgfmt/format.go
  vendor/google.golang.org/protobuf/testing/protocmp/reflect.go
  vendor/google.golang.org/protobuf/testing/protocmp/util.go
  vendor/google.golang.org/protobuf/testing/protocmp/xform.go
  vendor/modules.txt
Labels: port-to-otel-ebpf-inst

#1971 Fix http2 multiple connections issues
  bpf/gotracer/go_common.h
  bpf/gotracer/go_nethttp.c
  bpf/logger/bpf_dbg.h
  pkg/internal/ebpf/gotracer/gotracer.go
  pkg/internal/ebpf/logger/logger.go
  test/integration/http2go_test.go
Labels: port-to-otel-ebpf-inst

#1983 Ensure request types match when correlating
  bpf/common/trace_common.h
Labels: port-to-otel-ebpf-inst

#1982 Move Prometheus goroutine start to work for Alloy too
  pkg/export/prom/prom.go
Labels: port-to-otel-ebpf-inst

#2001 Fix bad trace propagation patch
  bpf/common/trace_common.h
  bpf/common/tracing.h
  bpf/gotracer/go_nethttp.c
  bpf/logger/bpf_dbg.h
Labels: port-to-otel-ebpf-inst
