Repository grafana/beyla, pull requests merged in 2025-04, with the labels that each got.

#1784 Fix span status report
  pkg/export/otel/metrics.go
  pkg/export/otel/traces.go
  pkg/export/otel/traces_test.go
  pkg/export/prom/prom.go
  pkg/internal/ebpf/common/fast_cgi_detect_transform.go
  pkg/internal/request/metric_attributes.go
  pkg/internal/request/span.go
  pkg/internal/request/span_getters.go
  test/integration/red_test.go
Labels: bug

#1815 Fetch cluster name from nodes labels
  pkg/internal/kube/informer_provider.go
  pkg/internal/netolly/transform/k8s/kubernetes.go
  pkg/transform/clustername.go
  pkg/transform/k8s.go
  test/integration/configs/instrumenter-config-go-otel-grpc.yml
  test/integration/configs/instrumenter-config-go-otel.yml
  test/integration/configs/instrumenter-config-promscrape.yml
  test/integration/configs/instrumenter-config.yml
  test/integration/k8s/common/k8s_metrics_testfuncs.go
  test/integration/k8s/daemonset/k8s_daemonset_traces_test.go
  test/integration/k8s/daemonset_python/k8s_daemonset_traces_test.go
  test/integration/k8s/manifests/00-kind-multi-node.yml
  test/integration/k8s/manifests/00-kind-multi-zone.yml
  test/integration/k8s/manifests/00-kind.yml
  test/integration/k8s/manifests/05-instrumented-service-otel.yml
  test/integration/k8s/manifests/05-instrumented-service-prometheus.yml
  test/integration/k8s/manifests/06-beyla-all-processes.yml
  test/integration/k8s/manifests/06-beyla-daemonset-disable-informers.yml
  test/integration/k8s/manifests/06-beyla-daemonset-multi-node-l7.yml
  test/integration/k8s/manifests/06-beyla-daemonset-multi-node.yml
  test/integration/k8s/manifests/06-beyla-daemonset-python.yml
  test/integration/k8s/manifests/06-beyla-daemonset.yml
  test/integration/k8s/manifests/06-beyla-netolly-dropexternal.yml
  test/integration/k8s/otel/k8s_otel_traces_test.go
  test/integration/k8s/owners/k8s_daemonset_metadata_test.go
  test/integration/k8s/owners/k8s_statefulset_metadata_test.go
Labels: bug

#1833 Fix iface attribute on socket http tracer
  bpf/netolly/flows_sock.c
Labels: bug

#1836 Fix batcher configuration for internal OTEL metrics exporter
  pkg/export/otel/metrics_internal.go
  pkg/export/otel/traces.go
Labels: bug

#1858 Allow periods in route heuristics
  pkg/internal/transform/route/cluster.go
  pkg/internal/transform/route/cluster_test.go
Labels: bug, port-to-otel-ebpf-inst

#1861 Ensure target_info and traces_target_info are consistent with the instrumentation state
  pkg/export/otel/common.go
  pkg/export/otel/expirer_test.go
  pkg/export/otel/metrics.go
  pkg/export/otel/metrics_proc_test.go
  pkg/export/otel/metrics_test.go
  pkg/export/prom/prom.go
  pkg/export/prom/prom_test.go
  pkg/internal/appolly/appolly.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/typer.go
  pkg/internal/discover/watcher_proc.go
  pkg/internal/exec/procevent.go
  pkg/internal/pipe/instrumenter.go
  pkg/internal/pipe/instrumenter_test.go
  pkg/internal/svc/svc.go
  pkg/internal/traces/read_decorator.go
  pkg/transform/k8s.go
Labels: port-to-otel-ebpf-inst

#1862 fix: HTTP2 header check causes panic
  pkg/internal/ebpf/common/http2grpc_transform.go
  pkg/internal/ebpf/common/http2grpc_transform_test.go
Labels: port-to-otel-ebpf-inst
