Repository grafana/beyla, pull requests merged in 2025-02, with the labels that each got.

#1573 Add documenation on Beyla's performance
  docs/sources/performance.md
Labels: documentation

#1614 Remove distributed traces limitation
  docs/sources/_index.md
Labels: documentation, backport, 2.0, backport-2.0, backport release-2.0, missing-labels

#1587 Introduce documentation about required capabilities
  docs/sources/_index.md
  docs/sources/security.md
  docs/sources/setup/kubernetes.md
Labels: documentation

#1632 Helm chart: do not override network flows attributes
  charts/beyla/values.yaml
Labels: breaking-change

#1649 Add AKS/EKS instructions
  docs/sources/security.md
Labels: documentation

#1660 Detect if running on host network before enabling context propagation
  pkg/internal/ebpf/common/common_darwin.go
  pkg/internal/ebpf/common/common_linux.go
  pkg/internal/ebpf/tctracer/tctracer.go
Labels: backport

#1664 Run protocol detector always on sock msg
  bpf/tc_sock.h
  pkg/internal/ebpf/tctracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_x86_bpfel.o
Labels: backport

#1674 Fix Network pipeline in Alloy
  pkg/export/prom/prom_net.go
Labels: bug

#1672 Fix process metrics dashboard
  ops/beyla-mixin/dashboards/application_process.json
Labels: bug

#1688 Fix OTEL HTTP exclusion detection
  pkg/internal/request/span.go
  pkg/internal/request/span_test.go
Labels: bug, backport release-2.0, type/bug

#1696 Documenting inter-zone traffic
  docs/sources/configure/export-data.md
  docs/sources/network/_index.md
  docs/sources/network/inter-az.md
Labels: type/docs

#1705 Fix example deployment
  deployments/03-instrumented-app.yml
  docs/sources/setup/kubernetes.md
Labels: backport release-2.0, type/docs
