Repository grafana/beyla, pull requests merged in 2025-01, with the labels that each got.

#1512 Defaults OTEL metrics interval to 60s
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/export/otel/metrics.go
  pkg/export/otel/metrics_test.go
  pkg/internal/ebpf/tcmanager/tcmanager.go
  pkg/internal/ebpf/tcmanager/tcmanager_test.go
  pkg/internal/ebpf/tcmanager/util.go
  pkg/internal/netolly/ebpf/sock_tracer_nolinux.go
  pkg/internal/netolly/ebpf/tracer_nonlinux.go
Labels: breaking-change

#1520 Stop Beyla if either NetO11y or AppO11y component fails [1.9-backport]
  pkg/components/beyla.go
  pkg/internal/discover/watcher_proc.go
Labels: backport-1.9, bug

#1425 Export internal metrics using OTEL metrics
  charts/beyla/Chart.yaml
  charts/beyla/README.md
  charts/beyla/templates/daemon-set.yaml
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/components/beyla.go
  pkg/export/otel/metrics.go
  pkg/export/otel/metrics_internal.go
  pkg/export/otel/metrics_net.go
  pkg/internal/imetrics/imetrics.go
Labels: breaking-change

#1529 Fix node name resolution in kubernetes
  pkg/internal/kube/informer_provider.go
Labels: bug

#1536 Exclude system services (self-instrumentation) by default
  charts/beyla/values.yaml
  docs/sources/configure/options.md
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/internal/discover/attacher.go
  pkg/internal/discover/attacher_test.go
  pkg/internal/discover/matcher.go
  pkg/services/criteria.go
Labels: breaking-change

#1545 RFC: Add documentation for Cilium support
  docs/sources/cilium-compatibility.md
Labels: documentation, 2.0

#1568 Remove BEYLA_PRINT_TRACES deprecated option
  pkg/beyla/config.go
  pkg/beyla/config_test.go
  pkg/export/debug/debug.go
  test/integration/docker-compose-grpc-http2-mux.yml
Labels: breaking-change

#1570 Remove hidden/deprecated configuration values
  pkg/components/beyla.go
  pkg/export/attributes/attr_defs.go
  pkg/export/otel/metrics.go
  pkg/export/prom/prom.go
  test/integration/configs/instrumenter-config-elixir.yml
  test/integration/configs/instrumenter-config-go-otel-grpc.yml
  test/integration/configs/instrumenter-config-go-otel.yml
  test/integration/configs/instrumenter-config-grpc-export.yml
  test/integration/configs/instrumenter-config-grpc-http2-mux.yml
  test/integration/configs/instrumenter-config-http2.yml
  test/integration/configs/instrumenter-config-java-host.yml
  test/integration/configs/instrumenter-config-java.yml
  test/integration/configs/instrumenter-config-multiexec-host.yml
  test/integration/configs/instrumenter-config-multiexec.yml
  test/integration/configs/instrumenter-config-no-route.yml
  test/integration/configs/instrumenter-config-node.yml
  test/integration/configs/instrumenter-config-other-grpc.yml
  test/integration/configs/instrumenter-config-override-svcname.yml
  test/integration/configs/instrumenter-config-php.yml
  test/integration/configs/instrumenter-config-promscrape.yml
  test/integration/configs/instrumenter-config-ruby.yml
  test/integration/configs/instrumenter-config.yml
  test/integration/docker-compose-1.16.yml
  test/integration/docker-compose-1.17.yml
  test/integration/docker-compose-client.yml
  test/integration/docker-compose-dotnet.yml
  test/integration/docker-compose-elixir.yml
  test/integration/docker-compose-go-otel-grpc.yml
  test/integration/docker-compose-go-otel.yml
  test/integration/docker-compose-grpc-http2-mux.yml
  test/integration/docker-compose-http2.yml
  test/integration/docker-compose-java-host.yml
  test/integration/docker-compose-java-pid.yml
  test/integration/docker-compose-java-system-wide.yml
  test/integration/docker-compose-java.yml
  test/integration/docker-compose-multiexec-host.yml
  test/integration/docker-compose-multiexec.yml
  test/integration/docker-compose-nodeclient.yml
  test/integration/docker-compose-nodejs.yml
  test/integration/docker-compose-other-grpc.yml
  test/integration/docker-compose-php-fpm-sock.yml
  test/integration/docker-compose-php-fpm.yml
  test/integration/docker-compose-python-sql.yml
  test/integration/docker-compose-python.yml
  test/integration/docker-compose-ruby.yml
  test/integration/docker-compose-rust.yml
  test/integration/docker-compose.yml
  test/integration/k8s/manifests/05-instrumented-service-otel.yml
  test/integration/k8s/manifests/05-instrumented-service-prometheus.yml
  test/integration/k8s/manifests/06-beyla-daemonset-disable-informers.yml
  test/integration/k8s/manifests/06-beyla-daemonset-multi-node-l7.yml
  test/integration/k8s/manifests/06-beyla-daemonset-multi-node.yml
  test/integration/k8s/manifests/06-beyla-daemonset-python.yml
  test/integration/k8s/manifests/06-beyla-daemonset.yml
  test/integration/k8s/manifests/06-beyla-external-informer.yml
  test/integration/k8s/manifests/06-instrumented-client-prom.template.yml
  test/integration/k8s/manifests/06-instrumented-client.template.yml
  test/integration/k8s/manifests/06-instrumented-grpc-client-prom.template.yml
  test/integration/k8s/manifests/06-instrumented-grpc-client.template.yml
  test/integration/k8s/manifests/07-instrumented-service-otel-kprobes.yml
Labels: breaking-change

#1575 Fix direct packet access
  bpf/tc_tracer.c
  bpf/tc_tracer_l7.h
  pkg/internal/ebpf/generictracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/gpuevent/bpf_arm64_bpfel.o
  pkg/internal/ebpf/gpuevent/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/gpuevent/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/gpuevent/bpf_x86_bpfel.o
  pkg/internal/ebpf/httptracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/httptracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/httptracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/httptracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/watcher/bpf_arm64_bpfel.o
  pkg/internal/ebpf/watcher/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/watcher/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/watcher/bpf_x86_bpfel.o
  pkg/internal/netolly/ebpf/net_arm64_bpfel.o
  pkg/internal/netolly/ebpf/net_x86_bpfel.o
  pkg/internal/netolly/ebpf/netsk_arm64_bpfel.o
  pkg/internal/netolly/ebpf/netsk_x86_bpfel.o
Labels: 2.0, bug

#1578 Update attributes semantic conventions OTEL v1.30.0
  pkg/export/attributes/attr_defs.go
  pkg/export/attributes/names/attrs.go
  pkg/export/otel/traces.go
  pkg/export/otel/traces_test.go
  pkg/internal/request/metric_attributes.go
  pkg/internal/request/span.go
  pkg/internal/request/span_getters.go
  test/integration/test_utils.go
  test/oats/redis/yaml/oats_go_redis.yaml
  test/oats/redis/yaml/oats_go_redis_fails.yaml
  test/oats/redis/yaml/oats_redis.yaml
  test/oats/sql/yaml/oats_sql.yaml
  test/oats/sql/yaml/oats_sql_go_postgres.yaml
  test/oats/sql/yaml/oats_sql_other_langs.yaml
  test/oats/sql/yaml/oats_sql_other_langs_args.yaml
  test/oats/sql/yaml/oats_sql_other_langs_mysql.yaml
  test/oats/sql/yaml/oats_sql_other_langs_prep.yaml
  test/oats/sql/yaml/oats_sql_other_langs_prep_mysql.yaml
  test/oats/sql/yaml/oats_sql_statement.yaml
Labels: breaking-change

#1584 Verify Cilium only if TC is going to be enabled
  pkg/beyla/config.go
  pkg/beyla/config_test.go
Labels: backport

#1589 Fix go http2 internal support
  bpf/go_grpc.h
  bpf/go_nethttp.h
  configs/offsets/tracker_input.json
  pkg/internal/ebpf/generictracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_x86_bpfel.o
  pkg/internal/goexec/offsets.json
  pkg/internal/goexec/structmembers.go
Labels: backport

#1596 Fix context propagation Go TLS bug
  bpf/go_nethttp.h
  bpf/protocol_http.h
  bpf/protocol_tcp.h
  bpf/tc_sock.h
  bpf/trace_common.h
  pkg/internal/ebpf/generictracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/generictracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_arm64_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_debug_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_tp_x86_bpfel.o
  pkg/internal/ebpf/gotracer/bpf_x86_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_arm64_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_debug_x86_bpfel.o
  pkg/internal/ebpf/tctracer/bpf_x86_bpfel.o
Labels: backport
